language: node_js

node_js:
  - 7

services:
  - mysql

branches:
  only:
    - master

env:
  - SYNC=true USE_ENVS=true DB_DIALECT=mysql DB_USERNAME=travis DB_NAME=test DB_HOST=127.0.0.1 DB_PORT=3306

cache:
  directories:
    - node_modules

before_script:
  - npm install
  - "mysql -e 'create database test;'"

script:
  - npm test

after_success:
  - npm run cover